apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: aspnetcore
    role: blue # Updated to 'green' later
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: aspnetcore
    role: blue # Updated to 'green' later
  ports:
  - port: 80
    targetPort: 80
