apiVersion: v1
kind: Service
metadata:
  name: blue-test-service
  labels:
    app: aspnetcore
    role: blue
    env: test
spec:
  type: LoadBalancer
  selector:
    app: aspnetcore
    role: blue
  ports:
  - port: 9000
    targetPort: 80
