apiVersion: v1
kind: Service
metadata:
  name: green-test-service
  labels:
    app: aspnetcore
    role: green
    env: test
spec:
  type: LoadBalancer
  selector:
    app: aspnetcore
    role: green
  ports:
  - port: 9001
    targetPort: 80
